version: "3"

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "19090:9090"
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
      POSTGRES_HOST: localhost
    ports:
      - "5432:5432"

  filmgrpc:
    build: .
    ports:
      - "50051:50051"
    depends_on:
      - postgres